FROM golang:1.11 AS deps
RUN mkdir -p /go/src/github.com/nicholasdille/insulatr
WORKDIR /go/src/github.com/nicholasdille/insulatr
COPY go.mod go.sum ./
ENV GO111MODULE=on
RUN go mod download
RUN find /go -type d

FROM golang:1.11 AS builder
COPY --from=deps /go/pkg /go/pkg
RUN find /go -type d

FROM scratch AS insulatr
COPY --from=builder /go/src/github.com/nicholasdille/insulatr/bin/insulatr /insulatr
ENTRYPOINT [ "/insulatr" ]
