settings:
  volume_name: myvolume
  working_directory: /src
  shell: [ "sh", "-x", "-e" ]
  network_name: mynetwork

repos:
  - name: main
    location: https://github.com/docker/app
    shallow: true
    directory: app
  - name: main
    location: https://github.com/docker/distribution
    shallow: true
    directory: distribution

services:
  - name: web
    image: nginx
  - name: mysql
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  - name: dind
    image: docker:dind
    privileged: true

steps:

  - name: test
    image: alpine
    environment:
      - TEST=foobar
    commands:
      - pwd
      - ls -l
      - ip a
      - printenv
      - df
      - test -f app/.git/shallow

  - name: web
    image: alpine
    commands:
      - apk update
      - apk add curl
      - curl -s web

  - name: user
    image: alpine
    user: 1000
    commands:
      - id -u

  - name: entrypoint
    image: alpine/git
    override_entrypoint: true
    commands:
      - pwd

  - name: build
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
    commands:
      - docker version

  - name: dood
    image: docker:stable
    mount_docker_sock: true
    commands:
      - docker version
