settings:
  shell: [ "sh", "-x", "-e" ]

repos:
  - name: insulatr
    location: https://github.com/nicholasdille/insulatr
    shallow: true
    directory: .

services:
  - name: dind
    image: docker:dind
    privileged: true
    suppress_log: true

steps:

  - name: build
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - HUB_USER
      - HUB_PASS
    commands:
      - printenv
      #- docker build --tag insulatr:latest .
