settings:
  shell: [ "sh", "-x", "-e" ]

repos:
  - name: insulatr
    location: https://github.com/nicholasdille/insulatr
    shallow: true
    directory: go/src/github.com/nicholasdille/insulatr

services:
  - name: dind
    image: docker:dind
    privileged: true
    suppress_log: true

files:
  - inject: Dockerfile
    content: |
      FROM scratch
      COPY /go/src/github.com/nicholasdille/insulatr/bin/insulatr-x86_64 /insulatr
      ENTRYPOINT [ "/insulatr" ]

steps:

  - name: build
    image: golang:1.11
    commands:
      - curl https://glide.sh/get | sh
      - cd go/src/github.com/nicholasdille/insulatr
      - glide install
      - make static

  - name: docker
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
    commands:
      - docker build --tag insulatr:latest .
