name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04
    container: golang:1.14

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test golang
      run: go version

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: make static

    - name: Test
      run: ./bin/insulatr-x86_64 --version
